<a href="https://colab.research.google.com/github/Olufunke2580/Olufunke_Data_Analysis_Portfolio/blob/main/Movie_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Loading TMBD Dataset
df = pd.read_csv('/content/TMBD Movie Dataset.csv')

In [ ]:
#Viewing the first 5 rows
df.head()

,Unnamed: 0,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,...,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj,profit,popularity_level
0,0,135397,tt0369610,32.985763,150000000.0,1.513529e+09,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,...,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015-06-09,5562,6.5,2015,1.379999e+08,1.392446e+09,1.363529e+09,High
1,1,76341,tt1392190,28.419936,150000000.0,3.784364e+08,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,...,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,2015-05-13,6185,7.1,2015,1.379999e+08,3.481613e+08,2.284364e+08,High
2,2,262500,tt2908446,13.112507,110000000.0,2.952382e+08,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,...,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2015-03-18,2480,6.3,2015,1.012000e+08,2.716190e+08,1.852382e+08,High
3,3,140607,tt2488496,11.173104,200000000.0,2.068178e+09,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,...,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,2015-12-15,5292,7.5,2015,1.839999e+08,1.902723e+09,1.868178e+09,High
4,4,168259,tt2820852,9.335014,190000000.0,1.506249e+09,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,...,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015-04-01,2947,7.3,2015,1.747999e+08,1.385749e+09,1.316249e+09,High

In [ ]:
#Check for columns
df.columns

Index(['Unnamed: 0', 'id', 'imdb_id', 'popularity', 'budget', 'revenue',
       'original_title', 'cast', 'homepage', 'director', 'tagline', 'keywords',
       'overview', 'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj', 'profit', 'popularity_level'],
      dtype='object')

In [ ]:
#check for data dimensions
df.shape
#We have 1287 rows and 24 columns

(1287, 24)

In [ ]:
#Check basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1287 entries, 0 to 1286
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            1287 non-null   int64
 1   id                    1287 non-null   int64
 2   imdb_id               1287 non-null   object
 3   popularity            1287 non-null   float64
 4   budget                1287 non-null   float64
 5   revenue               1287 non-null   float64
 6   original_title        1287 non-null   object
 7   cast                  1287 non-null   object
 8   homepage              1287 non-null   object
 9   director              1287 non-null   object
 10  tagline               1287 non-null   object
 11  keywords              1287 non-null   object
 12  overview              1287 non-null   object
 13  runtime               1287 non-null   int64
 14  genres                1287 non-null   object
 15  production_companies  1287 non-null   object
 16  release_date          1287 non-null   object
 17  vote_count            1287 non-null   int64
 18  vote_average          1287 non-null   float64
 19  release_year          1287 non-null   int64
 20  budget_adj            1287 non-null   float64
 21  revenue_adj           1287 non-null   float64
 22  profit                1287 non-null   float64
 23  popularity_level      1286 non-null   object
dtypes: float64(7), int64(5), object(12)
memory usage: 241.4+ KB

In [ ]:
#Checking for missing values
df.isnull().sum()
#Popularity_level has one missing value

Unnamed: 0              0
id                      0
imdb_id                 0
popularity              0
budget                  0
revenue                 0
original_title          0
cast                    0
homepage                0
director                0
tagline                 0
keywords                0
overview                0
runtime                 0
genres                  0
production_companies    0
release_date            0
vote_count              0
vote_average            0
release_year            0
budget_adj              0
revenue_adj             0
profit                  0
popularity_level        1
dtype: int64

In [ ]:
#Checking for the unique values in Popularity_level
df['popularity_level'].unique()

 #We have High', 'Moderately High', 'Medium', 'Low', nan.

In [ ]:
#check for duplicated rows
df.duplicated().sum()      # No duplicated rows

0

In [ ]:
# check for descriptive statistics
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,1287.0,4.125843e+03,2.671937e+03,0.000000e+00,1.972000e+03,3.523000e+03,6.554500e+03,1.076000e+04
id,1287.0,5.255749e+04,7.445008e+04,1.100000e+01,5.851500e+03,2.017800e+04,6.220950e+04,3.333480e+05
popularity,1287.0,1.786022e+00,2.172137e+00,1.033500e-02,6.647835e-01,1.152354e+00,2.125342e+00,3.298576e+01
budget,1287.0,5.200349e+07,5.514540e+07,1.000000e+00,1.400000e+07,3.200000e+07,7.000000e+07,4.250000e+08
revenue,1287.0,1.762444e+08,2.538156e+08,4.300000e+01,2.565097e+07,8.208716e+07,2.140694e+08,2.781506e+09
runtime,1287.0,1.102735e+02,1.881137e+01,6.300000e+01,9.700000e+01,1.070000e+02,1.210000e+02,2.010000e+02
vote_count,1287.0,9.472665e+02,1.255476e+03,1.000000e+01,1.790000e+02,4.390000e+02,1.173000e+03,9.767000e+03
vote_average,1287.0,6.279487e+00,7.959552e-01,2.200000e+00,5.800000e+00,6.300000e+00,6.800000e+00,8.300000e+00
release_year,1287.0,2.007017e+03,8.060503e+00,1.961000e+03,2.005000e+03,2.009000e+03,2.011000e+03,2.015000e+03
budget_adj,1287.0,5.462994e+07,5.525463e+07,9.693980e-01,1.519180e+07,3.556927e+07,7.630125e+07,4.250000e+08
revenue_adj,1287.0,1.991775e+08,2.968515e+08,4.300000e+01,2.764890e+07,8.674770e+07,2.351178e+08,2.827124e+09
profit,1287.0,1.242409e+08,2.183462e+08,-4.139124e+08,3.142641e+06,4.524300e+07,1.470070e+08,2.544506e+09

In [ ]:
#drop unnecessary columns
col = ['homepage', 'tagline', 'overview', 'cast','director',
       'keywords','overview','production_companies']
df.drop(col, axis=1, inplace=True)

In [ ]:
df.head(2)

,Unnamed: 0,id,imdb_id,popularity,budget,revenue,original_title,runtime,genres,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj,profit,popularity_level
0,0,135397,tt0369610,32.985763,150000000.0,1.513529e+09,Jurassic World,124,Action|Adventure|Science Fiction|Thriller,2015-06-09,5562,6.5,2015,1.379999e+08,1.392446e+09,1.363529e+09,High
1,1,76341,tt1392190,28.419936,150000000.0,3.784364e+08,Mad Max: Fury Road,120,Action|Adventure|Science Fiction|Thriller,2015-05-13,6185,7.1,2015,1.379999e+08,3.481613e+08,2.284364e+08,High

In [ ]:
#Renaming some columns' name
df.rename(columns={'vote_average':'Rating'})

,Unnamed: 0,id,imdb_id,popularity,budget,revenue,original_title,runtime,genres,release_date,vote_count,Rating,release_year,budget_adj,revenue_adj,profit,popularity_level
0,0,135397,tt0369610,32.985763,150000000.0,1.513529e+09,Jurassic World,124,Action|Adventure|Science Fiction|Thriller,2015-06-09,5562,6.5,2015,1.379999e+08,1.392446e+09,1.363529e+09,High
1,1,76341,tt1392190,28.419936,150000000.0,3.784364e+08,Mad Max: Fury Road,120,Action|Adventure|Science Fiction|Thriller,2015-05-13,6185,7.1,2015,1.379999e+08,3.481613e+08,2.284364e+08,High
2,2,262500,tt2908446,13.112507,110000000.0,2.952382e+08,Insurgent,119,Adventure|Science Fiction|Thriller,2015-03-18,2480,6.3,2015,1.012000e+08,2.716190e+08,1.852382e+08,High
3,3,140607,tt2488496,11.173104,200000000.0,2.068178e+09,Star Wars: The Force Awakens,136,Action|Adventure|Science Fiction|Fantasy,2015-12-15,5292,7.5,2015,1.839999e+08,1.902723e+09,1.868178e+09,High
4,4,168259,tt2820852,9.335014,190000000.0,1.506249e+09,Furious 7,137,Action|Crime|Thriller,2015-04-01,2947,7.3,2015,1.747999e+08,1.385749e+09,1.316249e+09,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,10595,253,tt0070328,1.549139,7000000.0,1.617778e+08,Live and Let Die,121,Adventure|Action|Thriller,1973-07-05,293,6.1,1973,3.437812e+07,7.945168e+08,1.547778e+08,Moderately High
1283,10689,660,tt0059800,1.910465,11000000.0,1.411957e+08,Thunderball,130,Adventure|Action|Thriller,2065-12-16,331,6.3,1965,7.612620e+07,9.771535e+08,1.301957e+08,Moderately High
1284,10724,668,tt0064757,1.778746,7000000.0,8.197449e+07,On Her Majesty's Secret Service,142,Adventure|Action|Thriller,2069-12-12,258,6.4,1969,4.160985e+07,4.872780e+08,7.497449e+07,Moderately High
1285,10759,948,tt0077651,1.198849,300000.0,7.000000e+07,Halloween,91,Horror|Thriller,1978-10-25,522,7.3,1978,1.002810e+06,2.339890e+08,6.970000e+07,Moderately High
1286,10760,8469,tt0077975,1.157930,2700000.0,1.410000e+08,Animal House,109,Comedy,1978-07-27,230,6.7,1978,9.025292e+06,4.713208e+08,1.383000e+08,Moderately High

In [ ]:
#Lets check the columns remaining
df.columns

Index(['Unnamed: 0', 'id', 'imdb_id', 'popularity', 'budget', 'revenue',
       'original_title', 'runtime', 'genres', 'release_date', 'vote_count',
       'vote_average', 'release_year', 'budget_adj', 'revenue_adj', 'profit',
       'popularity_level'],
      dtype='object')

In [ ]:
#Spliting genre columns using 'apply(pd.Series)' as the number to be splitted to varies
df_split = df['genres'].str.split('|').apply(pd.Series)
print(df_split)

              0                1                2         3    4
0        Action        Adventure  Science Fiction  Thriller  NaN
1        Action        Adventure  Science Fiction  Thriller  NaN
2     Adventure  Science Fiction         Thriller       NaN  NaN
3        Action        Adventure  Science Fiction   Fantasy  NaN
4        Action            Crime         Thriller       NaN  NaN
...         ...              ...              ...       ...  ...
1282  Adventure           Action         Thriller       NaN  NaN
1283  Adventure           Action         Thriller       NaN  NaN
1284  Adventure           Action         Thriller       NaN  NaN
1285     Horror         Thriller              NaN       NaN  NaN
1286     Comedy              NaN              NaN       NaN  NaN

[1287 rows x 5 columns]

In [ ]:
genre_split = df['genres'].str.split('|').apply(pd.Series,1).stack().reset_index(level=1, drop=True)

<ipython-input-40-df98396ca778>:1: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  genre_split = df['genres'].str.split('|').apply(pd.Series,1).stack().reset_index(level=1, drop=True)

In [ ]:
df[['profit','vote_average']]

            profit  vote_average
0     1.363529e+09           6.5
1     2.284364e+08           7.1
2     1.852382e+08           6.3
3     1.868178e+09           7.5
4     1.316249e+09           7.3
...            ...           ...
1282  1.547778e+08           6.1
1283  1.301957e+08           6.3
1284  7.497449e+07           6.4
1285  6.970000e+07           7.3
1286  1.383000e+08           6.7

[1287 rows x 2 columns]